name: Deploy Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd:latest

  local_run:
    name: Pull the image and run in local docker
    needs: push_to_registry
    runs-on: self-hosted    
    steps:
      - name: Delete previous containers
        run: docker ps -aq --filter ancestor=${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd:latest | xargs docker rm -f;

      - name: Delete previous images
        run: docker images -q ${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd:latest | xargs docker rmi;

      - name: Local pull
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd:latest

      - name: Local run
        run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nodejs-ci-cd:latest
          
